name: Build and push image to Forge

on: [push]
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to private registry
        uses: docker/login-action@v3
        with:
          registry: "https://forge.cschuijt.nl"
          username: casper
          password: ${{ secrets.REGISTRY_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: 'forge.cschuijt.nl/casper-oci/${{ github.event.repository.name }}:latest'
